# Gradle memory config
org.gradle.jvmargs=-Xmx2G

# Minecraft Properties
minecraft_version=1.21.11

# Fabric Properties
loader_version=0.19.3
fabric_version=0.141.6
min_fabric_api_version=0.139.4

# Mod Properties
mod_version=2.5.1
maven_group=com.rijz
archives_base_name=notenoughcalculator

# REI
rei_version=21.11.816
min_rei_version=21.11.814

# ModMenu (optional)
modmenu_version=17.0.1-beta.1
min_modmenu_version=17.0.0
