# Gradle memory config
org.gradle.jvmargs=-Xmx2G

# Minecraft Properties
minecraft_version=26.2

# Fabric Properties
loader_version=0.19.3
fabric_version=0.158.0
min_fabric_api_version=0.152.1
fabric_language_kotlin_version=1.13.13+kotlin.2.4.10

# Mod Properties
mod_version=3.0.0
maven_group=com.rijz
archives_base_name=notenoughcalculator

# REI
rei_version=26.2.820

# Mod Menu
modmenu_version=20.0.1
min_modmenu_version=20.0.0

# SkyBlock API & Item List
skyblockapi_version=4.2.20
skyblockitemlist_version=0.0.20

