# Gradle memory config
org.gradle.jvmargs=-Xmx2G

# Minecraft Properties
minecraft_version=26.3

# Fabric Properties
loader_version=0.19.5
fabric_version=0.161.0
loom_version=1.18-SNAPSHOT
fabric_language_kotlin_version=1.14.1+kotlin.2.4.20

# Mod Properties
mod_version=3.1.0
maven_group=com.rijz
archives_base_name=notenoughcalculator

# REI
rei_version=26.3.823
cloth_basic_math_version=0.6.1

# Mod Menu
modmenu_version=21.0.0

# Dev Auth
devauth_version=1.2.2

# SkyBlock API & Item List
skyblockapi_version=4.2.32
skyblockitemlist_version=0.0.23

# Other
spotless_version=8.10.0
junit_version=6.1.3